// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskAnalysis.Infrastructure.Persistence;

#nullable disable

namespace RiskAnalysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RiskAnalysisDbContext))]
    [Migration("20260923132133_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.ImportLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Message")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("message");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_inserted");

                    b.Property<int>("RowsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("rows_received");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("rows_updated");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_logs");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_import_logs_instrument_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_import_logs_started_at");

                    b.ToTable("import_logs", null, t =>
                        {
                            t.HasComment("Журнал загрузки данных из внешних источников");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("board");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("engine");

                    b.Property<string>("FullName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly?>("HistoryFrom")
                        .HasColumnType("date")
                        .HasColumnName("history_from");

                    b.Property<DateOnly?>("HistoryTo")
                        .HasColumnType("date")
                        .HasColumnName("history_to");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Isin")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("isin");

                    b.Property<int?>("LotSize")
                        .HasColumnType("integer")
                        .HasColumnName("lot_size");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("market");

                    b.Property<string>("Sector")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sector");

                    b.Property<string>("SecurityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("security_type");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("short_name");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_instruments_is_active");

                    b.HasIndex("Ticker", "Board")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_ticker_board");

                    b.ToTable("instruments", null, t =>
                        {
                            t.HasComment("Справочник финансовых инструментов");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.MacroIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_macro_indicators");

                    b.HasIndex("Code", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_macro_indicators_code_date");

                    b.ToTable("macro_indicators", null, t =>
                        {
                            t.HasComment("Макроэкономические показатели Банка России");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("base_currency");

                    b.Property<int?>("BenchmarkInstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("benchmark_instrument_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("BenchmarkInstrumentId")
                        .HasDatabaseName("ix_portfolios_benchmark_instrument_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_portfolios_owner_user_id");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasComment("Инвестиционные портфели, выступающие объектом анализа риска");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_positions_instrument_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_positions_portfolio_id");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasComment("Позиции портфеля по финансовым инструментам");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Quote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<decimal?>("Turnover")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("turnover");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("ix_quotes_trade_date");

                    b.HasIndex("InstrumentId", "TradeDate")
                        .IsUnique()
                        .HasDatabaseName("ix_quotes_instrument_id_trade_date");

                    b.ToTable("quotes", null, t =>
                        {
                            t.HasComment("История дневных котировок финансовых инструментов");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.RiskCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("calculation_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_risk_calculations");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_risk_calculations_status");

                    b.HasIndex("PortfolioId", "CreatedAt")
                        .HasDatabaseName("ix_risk_calculations_portfolio_id_created_at");

                    b.ToTable("risk_calculations", null, t =>
                        {
                            t.HasComment("Журнал расчётов: параметры запуска и результаты");
                        });
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.ImportLog", b =>
                {
                    b.HasOne("RiskAnalysis.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_import_logs_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("RiskAnalysis.Domain.Entities.Instrument", "BenchmarkInstrument")
                        .WithMany()
                        .HasForeignKey("BenchmarkInstrumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_portfolios_instruments_benchmark_instrument_id");

                    b.Navigation("BenchmarkInstrument");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Position", b =>
                {
                    b.HasOne("RiskAnalysis.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_instruments_instrument_id");

                    b.HasOne("RiskAnalysis.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Quote", b =>
                {
                    b.HasOne("RiskAnalysis.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Quotes")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.RiskCalculation", b =>
                {
                    b.HasOne("RiskAnalysis.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Calculations")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_risk_calculations_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("RiskAnalysis.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Calculations");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
