CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE instruments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        ticker character varying(32) NOT NULL,
        short_name character varying(128) NOT NULL,
        full_name character varying(512),
        security_type character varying(16) NOT NULL,
        engine character varying(32) NOT NULL,
        market character varying(32) NOT NULL,
        board character varying(32) NOT NULL,
        currency character varying(8) NOT NULL,
        isin character varying(16),
        sector character varying(128),
        lot_size integer,
        is_active boolean NOT NULL,
        history_from date,
        history_to date,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_instruments PRIMARY KEY (id)
    );
    COMMENT ON TABLE instruments IS 'Справочник финансовых инструментов';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE macro_indicators (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        code character varying(16) NOT NULL,
        date date NOT NULL,
        value numeric(18,6) NOT NULL,
        CONSTRAINT pk_macro_indicators PRIMARY KEY (id)
    );
    COMMENT ON TABLE macro_indicators IS 'Макроэкономические показатели Банка России';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE import_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        source character varying(32) NOT NULL,
        instrument_id integer,
        date_from date,
        date_to date,
        rows_received integer NOT NULL,
        rows_inserted integer NOT NULL,
        rows_updated integer NOT NULL,
        status character varying(16) NOT NULL,
        message character varying(4096),
        started_at timestamp with time zone NOT NULL,
        finished_at timestamp with time zone NOT NULL,
        duration_ms integer NOT NULL,
        CONSTRAINT pk_import_logs PRIMARY KEY (id),
        CONSTRAINT fk_import_logs_instruments_instrument_id FOREIGN KEY (instrument_id) REFERENCES instruments (id) ON DELETE SET NULL
    );
    COMMENT ON TABLE import_logs IS 'Журнал загрузки данных из внешних источников';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE portfolios (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        owner_user_id uuid,
        name character varying(256) NOT NULL,
        description character varying(2048),
        base_currency character varying(8) NOT NULL,
        benchmark_instrument_id integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_portfolios PRIMARY KEY (id),
        CONSTRAINT fk_portfolios_instruments_benchmark_instrument_id FOREIGN KEY (benchmark_instrument_id) REFERENCES instruments (id) ON DELETE SET NULL
    );
    COMMENT ON TABLE portfolios IS 'Инвестиционные портфели, выступающие объектом анализа риска';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE quotes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        instrument_id integer NOT NULL,
        trade_date date NOT NULL,
        open numeric(18,6) NOT NULL,
        high numeric(18,6) NOT NULL,
        low numeric(18,6) NOT NULL,
        close numeric(18,6) NOT NULL,
        volume bigint,
        turnover numeric(20,2),
        CONSTRAINT pk_quotes PRIMARY KEY (id),
        CONSTRAINT fk_quotes_instruments_instrument_id FOREIGN KEY (instrument_id) REFERENCES instruments (id) ON DELETE CASCADE
    );
    COMMENT ON TABLE quotes IS 'История дневных котировок финансовых инструментов';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE positions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        portfolio_id integer NOT NULL,
        instrument_id integer NOT NULL,
        quantity numeric(18,6) NOT NULL,
        purchase_price numeric(18,6) NOT NULL,
        purchase_date date NOT NULL,
        note character varying(512),
        CONSTRAINT pk_positions PRIMARY KEY (id),
        CONSTRAINT fk_positions_instruments_instrument_id FOREIGN KEY (instrument_id) REFERENCES instruments (id) ON DELETE RESTRICT,
        CONSTRAINT fk_positions_portfolios_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
    );
    COMMENT ON TABLE positions IS 'Позиции портфеля по финансовым инструментам';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE TABLE risk_calculations (
        id uuid NOT NULL,
        portfolio_id integer NOT NULL,
        calculation_type character varying(32) NOT NULL,
        status character varying(16) NOT NULL,
        parameters_json jsonb NOT NULL,
        result_json jsonb,
        error_message character varying(4096),
        created_at timestamp with time zone NOT NULL,
        started_at timestamp with time zone,
        finished_at timestamp with time zone,
        duration_ms integer,
        CONSTRAINT pk_risk_calculations PRIMARY KEY (id),
        CONSTRAINT fk_risk_calculations_portfolios_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
    );
    COMMENT ON TABLE risk_calculations IS 'Журнал расчётов: параметры запуска и результаты';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_import_logs_instrument_id ON import_logs (instrument_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_import_logs_started_at ON import_logs (started_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_instruments_is_active ON instruments (is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE UNIQUE INDEX ix_instruments_ticker_board ON instruments (ticker, board);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE UNIQUE INDEX ix_macro_indicators_code_date ON macro_indicators (code, date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_portfolios_benchmark_instrument_id ON portfolios (benchmark_instrument_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_portfolios_owner_user_id ON portfolios (owner_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_positions_instrument_id ON positions (instrument_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_positions_portfolio_id ON positions (portfolio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE UNIQUE INDEX ix_quotes_instrument_id_trade_date ON quotes (instrument_id, trade_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_quotes_trade_date ON quotes (trade_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_risk_calculations_portfolio_id_created_at ON risk_calculations (portfolio_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    CREATE INDEX ix_risk_calculations_status ON risk_calculations (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923132133_InitialSchema') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260923132133_InitialSchema', '10.0.12');
    END IF;
END $EF$;
COMMIT;

